version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Password@12345"
      ACCEPT_EULA: "Y"
    ports:
    - "1433:1433"

  jdmarketsln.web.api:
    image: ${DOCKER_REGISTRY-}jdmarketslnwebapi
    build:
      context: .
      dockerfile: src/Web/JDMarketSLn.Web.Api/Dockerfile
    depends_on: 
      - db

  jdmarketsln.web.ui:
    image: ${DOCKER_REGISTRY-}jdmarketslnwebui
    build:
      context: .
      dockerfile: src/Web/JDMarketSLn.Web.UI/Dockerfile

